apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vmpool: talos-worker
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: talos-worker
        kubevirt.io/os: talos
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "lan-bridge" }]'
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-worker-disk
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 10Gi
            source:
              http:
                url: https://factory.talos.dev/image/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245/v1.9.5/metal-amd64.qcow2
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: talos-worker
        spec:
          domain:
            cpu:
              cores: 2
            resources:
              requests:
                memory: 2Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
              interfaces:
                - name: default
                  bridge: {}   
                - name: bridged
                  bridge: {}   
          networks:
            - name: default
              pod: {}
            - name: bridged
              multus:
                networkName: lan-bridge
          volumes:
            - name: disk0
              dataVolume:
                name: talos-worker-disk