apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cni-cleanup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cni-cleanup
  template:
    metadata:
      labels:
        app: cni-cleanup
    spec:
      tolerations:                # allow on control‑plane nodes
        - operator: Exists
      hostPID: true               # needed to touch host FS
      containers:
        - name: cleaner
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              set -e
              echo "Removing duplicate CNI configs on $(hostname)…"
              rm -f /host/etc/cni/net.d/10-canal.conflist
              rm -f /host/etc/cni/net.d/10-flannel.conflist
              echo "Done; sleeping so the pod stays Ready for Argo health‑check."
              sleep 86400
          volumeMounts:
            - name: host-cni
              mountPath: /host/etc/cni/net.d
      volumes:
        - name: host-cni
          hostPath:
            path: /etc/cni/net.d