apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos-control-plane
spec:
  replicas: 3
  selector:
    matchLabels:
      app: talos-control-plane
  virtualMachineTemplate:
    metadata:
      labels:
        app: talos-control-plane
        kubevirt.io/vmpool: talos-control-plane
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-controlplane-disk
          spec:
            storage:
              accessModes: ["ReadWriteOnce"]
              volumeMode: Filesystem
              resources:
                requests:
                  storage: {{ .Values.vCluster.controlPlane.storageSize }}Gi
            source:
              http:
                url: {{ .Values.vCluster.controlPlane.image }}
      template:
        metadata:
          labels:
            app: talos-control-plane
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: "kubernetes.io/hostname"
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - talos-control-plane
          domain:
            cpu:
              cores: {{ .Values.vCluster.controlPlane.cpuCores }}
            resources:
              requests:
                cpu: {{ .Values.vCluster.controlPlane.cpuCores }}
                memory: {{ .Values.vCluster.controlPlane.memory }}Gi
              limits:
                cpu: {{ .Values.vCluster.controlPlane.cpuCores }}
                memory: {{ .Values.vCluster.controlPlane.memory }}Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
          volumes:
            - name: disk0
              dataVolume:
                name: talos-controlplane-disk