apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: virtual-cluster-worker-scaler
  namespace: test
spec:
  maxReplicas: {{ .Values.maxWorkers }}
  minReplicas: {{ .Values.minWorkers }}
  scaleTargetRef:
    apiVersion: pool.kubevirt.io/v1alpha1
    kind: VirtualMachinePool
    name: talos-worker
  targetCPUUtilizationPercentage: {{ .Values.targetCPU }}