apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vCluster.ubuntuVM.name }}-ssh
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.vCluster.ubuntuVM.loadBalancerIP }}
  selector:
    kubevirt.io/domain: {{ .Values.vCluster.ubuntuVM.name }}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
