apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vmpool: talos-worker
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: talos-worker
        kubevirt.io/os: talos
      annotations:
        k8s.v1.cni.cncf.io/networks: default/lan-bridge
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-worker-disk
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: {{ .Values.vCluster.worker.storageSize }}Gi
            source:
              http:
                url: {{ .Values.vCluster.worker.image }}
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: talos-worker
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: "kubernetes.io/hostname"
                    labelSelector:
                      matchExpressions:
                        - key: kubevirt.io/vmpool
                          operator: In
                          values:
                            - talos-worker
          domain:
            cpu:
              cores: {{ .Values.vCluster.worker.cpuCores }}
            resources:
              requests:
                cpu: {{ .Values.vCluster.worker.cpuCores }}
                memory: {{ .Values.vCluster.worker.memory }}Gi
              limits:
                cpu: {{ .Values.vCluster.worker.cpuCores }}
                memory: {{ .Values.vCluster.worker.memory }}Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
              interfaces:
                - name: default
                  bridge: {}
                - name: bridged
                  bridge: {}
          networks:
            - name: default
              pod: {}
            - name: bridged
              multus:
                networkName: default/lan-bridge
          volumes:
            - name: disk0
              dataVolume:
                name: talos-worker-disk