apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vmpool: talos-worker
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: talos-worker
        kubevirt.io/os: talos
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-worker-disk
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 10Gi
            source:
              http:
                url: {{ .Values.workerImage }}
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: talos-worker
        spec:
          domain:
            cpu:
              cores: 2
            resources:
              requests:
                memory: 10Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
          volumes:
            - name: disk0
              dataVolume:
                name: talos-worker-disk
