apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: virtual-cluster-scaler
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: pool.kubevirt.io/v1alpha1
    kind: VirtualMachinePool
    name: talos-worker
  targetCPUUtilizationPercentage: 50
