apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.116
  path: /srv/nfs/k8s
reclaimPolicy: Retain
mountOptions:
  - hard
  - nfsvers=4.1
