apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage # Must match your StorageClass
  nfs:
    server: 192.168.0.116 # Your NFS server IP
    path: /srv/nfs/k8s # Your NFS export path
