apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubuntu
  namespace: argocd
spec:
  project: ubuntu
  source:
    repoURL: git@github.com:ulrikof/DCST2900-K8s.git
    targetRevision: main
    path: ArgoCD/projects/infra/ubuntu
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ubuntu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
