apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  forProvider:
    location: "West Europe"
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: default