apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: talos-worker-1
  labels:
    kubevirt.io/os: talos
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: talos-worker-1
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          volumeMode: Filesystem
          resources:
            requests:
              storage: 10Gi
        source:
          http:
            url: https://factory.talos.dev/image/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245/v1.9.5/metal-amd64.qcow2
  template:
    metadata:
      labels:
        kubevirt.io/domain: talos-worker-1
    spec:
      hostname: "talos-worker-1"
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
      volumes:
        - name: disk0
          dataVolume:
            name: talos-worker-1
