apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: virtual-cluster-worker-scaler
spec:
  maxReplicas: {{ .Values.hpa.maxWorkers }}
  minReplicas: {{ .Values.hpa.minWorkers }}
  scaleTargetRef:
    apiVersion: pool.kubevirt.io/v1alpha1
    kind: VirtualMachinePool
    name: talos-worker
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPU }}