apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros-vm
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: cirros-vm
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio # Can be scsi, sata, or virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 512Mi
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: cirros-vm-disk # This should match your uploaded PVC
      networks:
        - name: default
          pod: {}
