apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ulrikof/DCST2900-K8s.git
    targetRevision: main
    path: ArgoCD/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        createdby: argocd
    syncOptions:
      - Cascade=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - CreateNamespace=true
