apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: default
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: default
            name: universal-auth-credentials
      # Details to pull secrets from
      secretsScope:
        projectSlug: dsct2900-k8s-dfs-i
        environmentSlug: dev
        # optional
        secretsPath: /
        # optional
        recursive: true # Default is false
        # optional
        expandSecretReferences: false # Default is true
      # optional
      hostAPI: https://eu.infisical.com