apiVersion: v1
kind: Pod
metadata:
  name: north-busybox-1
  labels:
    app: north-busybox-1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: north-busybox-1-svc
spec:
  selector:
    app: north-busybox-1
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP