# Must be added to at least worker.yaml, unsure if needed in control-plane.yaml (propably not but does not hurt)

extraMounts:
  - destination: /var/lib/longhorn
    type: bind
    source: /var/lib/longhorn
    options:
      - bind
      - rshared
      - rw
