apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn.yaml

patches:
  - target:
      kind: Namespace
      name: longhorn-system
    path: namespace.yaml
  - target:
      kind: Service
      name: longhorn-frontend
      namespace: longhorn-system
    path: patch-longhorn-frontend-service.yaml
  - target:
      kind: Setting
      name: taint-toleration
      namespace: longhorn-system
    path: longhorn-setting-patch.yaml