apiVersion: database.azure.crossplane.io/v1beta1
kind: SQLServer
metadata:
  name: example-sqlserver
spec:
  forProvider:
    resourceGroupName: example-rg
    location: WestUS
    administratorLogin: myadmin
    administratorLoginPasswordSecretRef:
      name: sql-password
      key: password
    version: "12.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-password
  namespace: crossplane-system
type: Opaque
data:
  password: <base64-encoded-password>
---
apiVersion: database.azure.crossplane.io/v1beta1
kind: SQLDatabase
metadata:
  name: example-sqldatabase
spec:
  forProvider:
    resourceGroupName: example-rg
    serverName: example-sqlserver
    collation: SQL_Latin1_General_CP1_CI_AS
    maxSizeGB: 10
    sku:
      name: S0