apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # This is a global, cluster-wide secret store. Use SecretStore for namespaced secret stores.
metadata:
  name: doppler-auth-api
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: default