apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ulrikof/DCST2900-K8s.git
    targetRevision: main
    path: ArgoCD/deployments/addons/kubevirt/kubevirt-operator
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
