apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-cr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ulrikof/DCST2900-K8s.git
    targetRevision: main
    path: ArgoCD/deployments/addons/kubevirt/kubevirt-cr
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
