apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: kyverno
      repoURL: https://kyverno.github.io/kyverno
      targetRevision: 1.13.0
    # - repoURL: git@github.com:ulrikof/DCST2900-K8s.git
    #   # targetRevision: main
    #   path: ArgoCD/deployments/addons/kyverno
    # kustomize: {}
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - Cascade=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kyverno
#   namespace: argocd
# spec:
#   destination:
#     namespace: kyverno
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     chart: kyverno
#     repoURL: https://kyverno.github.io/kyverno
#     targetRevision: main
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - Replace=true
#       - Cascade=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
