{{- range .Values.org.users.adminUsers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin-binding-{{ .userName }}
  namespace: {{ $.Values.org.ns }}
subjects:
  - kind: User
    name: {{ .userName }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}