apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-ssh
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    kubevirt.io/domain: {{ .Values.name }}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
