apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos-worker
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vmpool: talos-worker
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: talos-worker
        kubevirt.io/os: talos
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-worker-disk
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 10Gi
            source:
              http:
                url: https://factory.talos.dev/image/56e8a3c8825122da93fd6ba4d43fbf6b02bf03bd07a0ddbfe90f818e1247922e/v1.9.5/metal-amd64.qcow2
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: talos-worker
        spec:
          domain:
            cpu:
              cores: 2
            resources:
              requests:
                memory: 2Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
              interfaces:
                - name: default
                  masquerade: {}
          networks:
            - name: default
              pod: {} # this connects the VM to the pod network
          volumes:
            - name: disk0
              dataVolume:
                name: talos-worker-disk
