apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: { { .Values.org } }
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:ulrikof/DCST2900-K8s.git
      targetRevision: network
      path: ArgoCD/manifests/org
  destination:
    namespace: { { .Values.org } }
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
