# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: north-org
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: https://github.com/ulrikof/DCST2900-K8s.git
#       targetRevision: main
#       path: ArgoCD/charts/org
#       helm:
#         valueFiles:
#           - ../../../ArgoCD/apps/orgs/north/values.yaml
#           # - ../../../ArgoCD/testing/orgs/north/values.yaml
#     # - repoURL: https://github.com/ulrikof/DCST2900-K8s.git
#     #   targetRevision: main
#     #   path: ArgoCD/charts/org-users
#     #   helm:
#     #     valueFiles:
#     #       - ../../../ArgoCD/apps/orgs/north/values.yaml
#     #       # - ../../../ArgoCD/testing/orgs/north/values.yaml
#     # - repoURL: https://github.com/ulrikof/DCST2900-K8s.git
#     #   targetRevision: main
#     #   path: ArgoCD/charts/busybox
#     #   helm:
#     #     valueFiles:
#     #       - ../../../ArgoCD/apps/orgs/north/values.yaml
#           # - ../../../ArgoCD/testing/orgs/north/values.yaml
#     - repoURL: https://github.com/ulrikof/DCST2900-K8s.git
#       targetRevision: main
#       path: ArgoCD/charts/k8s-in-k8s 
#       helm:
#         valueFiles:
#           - ../../../ArgoCD/apps/orgs/north/values.yaml
#     # #         - ../../../ArgoCD/testing/orgs/north/values.yaml

#   destination:
#     namespace: north-org
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true