# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: east-org
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: git@github.com:ulrikof/DCST2900-K8s.git
#       targetRevision: main
#       path: ArgoCD/charts/org
#       helm:
#         valueFiles:
#           - ../../../ArgoCD/apps/orgs/east/values.yaml
#     - repoURL: git@github.com:ulrikof/DCST2900-K8s.git
#       targetRevision: main
#       path: ArgoCD/charts/busybox
#       helm:
#         valueFiles:
#           - ../../../ArgoCD/apps/orgs/east/values.yaml
#   destination:
#     namespace: east-org
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true