apiVersion: v1
kind: Pod
metadata:
  name: im-a-stupid-cuck
  namespace: {{ .Values.ns }}
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always