apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: external-secrets
      name: azure-secrets-from-doppler
      key: CREDS

# THIS IS UNIQUE PER ORG