# The ArgoCD Application for the Azure providers ProviderConfig
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: external-secrets
      name: azure-secrets-from-doppler
      key: creds

# THIS IS UNIQUE PER ORG