apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-in-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ulrikof/DCST2900-K8s.git
    targetRevision: main
    path: ArgoCD/charts/k8s-in-k8s
    helm:
      values: |
        loadBalancerIP: 10.100.39.110
        configLbIP: 10.100.39.111
        controlPlaneImage: https://factory.talos.dev/image/38a5e9b9cfbaeb1054642d93fe3db18befe3e3e1d85a8a96524cdb9acb0643a6/v1.9.5/metal-amd64.qcow2
        workerImage: https://factory.talos.dev/image/6d7b96ad6996875a5a4588d15277e04cb032c0ba10f4208027721f0971aa944a/v1.9.5/metal-amd64.qcow2
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-in-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true