apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml

patches:
  - target:
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system
    path: multus-ds-patch.yaml
