apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-a
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        vm-group: vm-a
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: vm-group
                    operator: In
                    values:
                      - vm-b
              topologyKey: "kubernetes.io/hostname"
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 64Mi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=