apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaling-test
  minReplicas: 1
  maxReplicas: 3 # Action is to edit this to 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10  # target average CPU usage (50%)