{{- range .Values.org.users.adminUsers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin-binding-{{ . }}
  namespace: {{ $.Values.org.namespace }}
subjects:
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}