apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace-only
  namespace: {{ .Values.ns }}
spec:
  podSelector: {} # Apply to all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
                {{ .Values.org }}
  egress:
    - to:
        - podSelector:
            matchLabels:
                {{ .Values.org }}
    # - to:
    #     - namespaceSelector:
    #         matchLabels:
    #             kubernetes.io/metadata.name: kube-system
    #   ports:
    #     - protocol: UDP
    #       port: 53