apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace-only
  namespace: {{ .Values.org.ns }}
spec:
  podSelector: {} # Apply to all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                org: {{ .Values.org.name }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
                org: {{ .Values.org.name }}
    - to:
        - namespaceSelector:
            matchLabels:
                kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53