apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos-control-plane
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: talos-control-plane
  virtualMachineTemplate:
    metadata:
      labels:
        app: talos-control-plane
        kubevirt.io/vmpool: talos-control-plane
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-controlplane-disk
          spec:
            storage:
              accessModes: ["ReadWriteOnce"]
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 20Gi
            source:
              http:
                url: https://factory.talos.dev/image/37e5c8c4682afdcb9b5a1a98759d96c3190fea16bb88640d1095f4817e9ce6e0/v1.9.5/metal-amd64.qcow2
      template:
        metadata:
          labels:
            app: talos-control-plane
        spec:
          domain:
            cpu:
              cores: 2
            resources:
              requests:
                memory: 2Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
          volumes:
            - name: disk0
              dataVolume:
                name: talos-controlplane-disk
