apiVersion: v2
name: k8s-in-k8s
description: Helm chart to deploy a Talos-based Kubernetes cluster inside Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: ubuntu-vm
    version: 0.1.0
    repository: "file://../ubuntu-vm"