apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: south-org
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:ulrikof/DCST2900-K8s.git
      targetRevision: main
      path: ArgoCD/charts/org
      helm:
        valueFiles:
          - ../../../ArgoCD/apps/orgs/south/values.yaml
    - repoURL: git@github.com:ulrikof/DCST2900-K8s.git
      targetRevision: main
      path: ArgoCD/charts/busybox
      helm:
        valueFiles:
          - ../../../ArgoCD/apps/orgs/south/values.yaml
  destination:
    namespace: south-org
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: south-org
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/ulrikof/DCST2900-K8s.git
#     targetRevision: main
#     path: manifests/org
#     helm:
#       valueFiles:
#         - apps/orgs/south/values.yaml
#   destination:
#     namespace: south-org
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
