# apiVersion: v1
# kind: Namespace
# metadata:
#   name: test-busybox
# ---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-2
  namespace: test-busybox
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always
