name: Validate Kubernetes YAML

on:
  pull_request:
    paths:
      - '**/*.yaml'

jobs:
  kube-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar xz
          sudo mv kubeconform /usr/local/bin/
      - name: Validate manifests
        run: |
          find . -name '*.yaml' -print0 | xargs -0 kubeconform -strict -summary
