name: Validate Manifests

on:
  pull_request:
    branches: [main]

jobs:
  validate-k8s-manifests:
    name: Check syntax & formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint kubeval

      - name: Lint YAML (formatting)
        run: |
          yamllint -c .yamllint.yml .

      - name: Validate Kubernetes manifests (syntax/schema)
        run: |
          find . -name '*.yaml' -exec kubeval {} \;
